name: Build with BuildKit Rootless on ARC Runner

on:
  workflow_dispatch: # This line ensures the workflow can only be triggered manually

jobs:
  build:
    runs-on: gh-arc-runner-set # Or your specific ARC runner label, e.g., 'self-hosted-arc-linux'

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up BuildKit (buildctl and buildctl-daemonless.sh)
      run: |
        BUILDKIT_VERSION="v0.22.0" # Ensure this is the version you want
        ARCH="linux-amd64"       # Adjust for your runner's architecture

        # Create a temporary directory for extraction
        EXTRACT_DIR=$(mktemp -d -t buildkit-install-XXXXXX)
        echo "Extracting BuildKit to temporary directory: ${EXTRACT_DIR}"

        # Download BuildKit archive and extract to the temporary directory
        curl -sL https://github.com/moby/buildkit/releases/download/${BUILDKIT_VERSION}/buildkit-${BUILDKIT_VERSION}.${ARCH}.tar.gz \
          | tar -xz -C "${EXTRACT_DIR}"

        # Find the buildctl binary within the extracted directory
        BUILDC_BIN=$(find "${EXTRACT_DIR}" -name buildctl -print -quit)
        if [ -z "$BUILDC_BIN" ]; then
          echo "Error: buildctl binary not found in extracted archive."
          ls -R "${EXTRACT_DIR}" # List contents of temp dir for debugging
          exit 1
        fi
        echo "Found buildctl at: $BUILDC_BIN"
        sudo mv "$BUILDC_BIN" /usr/local/bin/buildctl
        sudo chmod +x /usr/local/bin/buildctl

        # Download buildctl-daemonless.sh
        echo "Downloading buildctl-daemonless.sh..."
        curl -sL https://raw.githubusercontent.com/moby/buildkit/${BUILDKIT_VERSION}/examples/buildctl-daemonless/buildctl-daemonless.sh \
          | sudo tee /usr/local/bin/buildctl-daemonless.sh > /dev/null

        sudo chmod +x /usr/local/bin/buildctl-daemonless.sh

        echo "BuildKit buildctl components installed at /usr/local/bin/"

        # Clean up the temporary extraction directory
        rm -rf "${EXTRACT_DIR}"

    - name: Verify buildctl is available
      run: |
        buildctl --version
        export XDG_RUNTIME_DIR="$(mktemp -d)"
        echo "XDG_RUNTIME_DIR set to: $XDG_RUNTIME_DIR"
        buildctl-daemonless.sh --version

    - name: Login to GitHub Container Registry (GHCR)
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}