name: Build and Push Docker Image (Kubernetes BuildKit)

on:
  workflow_dispatch: # This specifies a manual trigger with no custom inputs

jobs:
  build-image:
    runs-on: gh-arc-runner-set # Assumes your Kubernetes self-hosted runner is configured

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx with Kubernetes Driver
        uses: docker/setup-buildx-action@v3
        with:
          driver: kubernetes
          image: moby/buildkit:latest # Or moby/buildkit:rootless if preferred
          buildkitd-flags: --oci-worker-no-process-sandbox
          kubernetes-pod-annotations: |
            "kubernetes.io/security-context": '{ "runAsUser": 1000, "runAsGroup": 1000, "allowPrivilegeEscalation": false }'

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}:latest