name: Build Rootless Docker Image on Kubernetes

on:
  # Disabling push trigger
  # push:
  #   branches:
  #     - main
  workflow_dispatch: # Allows manual triggering of the workflow from the GitHub UI

jobs:
  build-rootless:
    runs-on: gh-arc-runner-set # Use your specific label for your self-hosted Kubernetes runner set

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up BuildKit with Kubernetes driver
      uses: docker/setup-buildx-action@v3
      with:
        driver: kubernetes
        driver-opts: |
          namespace=buildkit # Define the Kubernetes namespace for BuildKit pods
          rootless=true # Ensures BuildKit runs in rootless mode within the Kubernetes pods
        buildkitd-flags: |
          --oci-worker-no-process-sandbox # Your specific BuildKit daemon flag

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }} # Use your Docker Hub username secret
        password: ${{ secrets.DOCKER_TOKEN }}   # Use your Docker Hub Access Token secret

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.repository }}:${{ github.sha }} # Image will be tagged with your Docker Hub username/repository:commit_sha
        cache-from: type=gha,scope=${{ github.workflow }} # Leverage GitHub Actions cache for faster builds
        cache-to: type=gha,mode=max,scope=${{ github.workflow }} # Store build cache in GitHub Actions