name: Build and Push Image with BuildKit (Daemonless, Docker Hub)

on:
  workflow_dispatch:  # Manual trigger

jobs:
  build:
    runs-on: gh-arc-runner-set

    container:
      image: moby/buildkit:rootless

    env:
      BUILDKITD_FLAGS: --oci-worker-no-process-sandbox
      CI_REGISTRY: https://index.docker.io/v1/
      CI_REGISTRY_IMAGE: docker.io/ajaybabupothini/myapp
      CI_COMMIT_SHA: ${{ github.sha }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: |
          mkdir -p ~/.docker
          echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"${{ secrets.DOCKER_USERNAME }}\",\"password\":\"${{ secrets.DOCKER_TOKEN }}\"}}}" > ~/.docker/config.json

      - name: Build and push image with BuildKit
        run: |
          buildctl-daemonless.sh build \
            --frontend dockerfile.v0 \
            --local context=. \
            --local dockerfile=. \
            --output type=image,name=$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA,push=true
