name: Build and Push Docker Image (Kubernetes BuildKit)

on:
  workflow_dispatch: # This specifies a manual trigger with no custom inputs

jobs:
  build-image:
    runs-on: arc-runner-set # Assumes your Kubernetes self-hosted runner is configured
    permissions:
      contents: read
      packages: write
      attestations: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx with Kubernetes Driver
        uses: docker/setup-buildx-action@v3
        with:
          driver: kubernetes
          driver-opts: |
            rootless=true
            replicas=1
            limits.memory=800Mi
          buildkitd-flags: |
              --oci-worker-no-process-sandbox
              --debug





      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}:latest
        env:
          DOCKER_BUILD_SUMMARY: false