name: Build and Push Docker Image (GArifactory)

on:
  workflow_dispatch: # This specifies a manual trigger with no custom inputs

jobs:
  build-image:
    runs-on: arc-runner-set # Assumes your Kubernetes self-hosted runner is configured
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write # Required for Workload Identity Federation

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/888274222600/locations/global/workloadIdentityPools/my-pool/providers/my-provider' # Replace with your Workload Identity Provider
          service_account: 'github-actions-artifact-push@melodic-furnace-403022.iam.gserviceaccount.com' # Replace with your Service Account Email
          access_token_lifetime: 300s
          # OR, if using a service account key directly (less recommended for production):
          # credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Docker Buildx with Kubernetes Driver
        uses: docker/setup-buildx-action@v3
        with:
          driver: kubernetes
          driver-opts: |
            rootless=true
            replicas=1
            limits.memory=800Mi
          buildkitd-flags: |
            --oci-worker-no-process-sandbox
            --debug

      - name: Log in to GitHub Container Registry and Google Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/login-action@v3
        with:
          registry: us-east4-docker.pkg.dev # Example: us-central1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }} # Use the access token from the auth step
          # OR, if using a service account key directly:
          # password: ${{ secrets.GCP_SA_KEY }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}:latest
            us-east4-docker.pkg.dev/melodic-furnace-403022/cpc-docker-repo/${{ github.event.repository.name }}:${{ github.sha }}
            us-east4-docker.pkg.dev/melodic-furnace-403022/cpc-docker-repo/${{ github.event.repository.name }}:latest
        env:
          DOCKER_BUILD_SUMMARY: false